---
title: "Platform Comparisons"
always_allow_html: yes
output:
  html_document:
    code_folding: hide
    number_sections: yes
    toc: yes
    toc_depth: 5
    theme: united
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Overview
The expression levels measured by the three platforms (microarray, nCounter, and qPCR) were compared.


# Prepare the environment
```{r message=FALSE, warning=FALSE}
# Load packages.
library(magrittr) # Pipe operator.
library(ggplot2) # Plotting.
library(cowplot) # Plotting.
theme_set(theme_cowplot())
library(ggpubr) # Plotting.

# Create the Results folder.
if(dir.exists("Results")){
  unlink("Results", recursive = TRUE, force = TRUE)
}
dir.create("Results")
```


# Prepare the data
```{r message=FALSE, warning=FALSE}
# Define data file paths.
files <- file.path("Data", list.files("Data"))

# Load the data.
df <- lapply(
  files,
  function(input_file){
    readxl::read_excel(input_file)
  }
) %>%
  dplyr::bind_rows() %>%
  dplyr::mutate(
    Label = factor(Label, levels = c("AIUP","ECT")),
    Source = factor(Source, levels = c("Microarray","qPCR","nCounter"))
  ) %>%
  dplyr::filter(
    Gene %in% unique(Gene[Source == "Microarray"])
  ) %>%
  dplyr::group_by(Source, Gene) %>%
  dplyr::mutate(Expression = Expression/max(Expression)) %>%
  dplyr::ungroup() %>%
  tidyr::spread(Source, Expression)
```


# Determine correlations
```{r message=FALSE, warning=FALSE}
cors <- tibble::data_frame(
  A = c("Microarray", "Microarray", "qPCR"),
  B = c("qPCR", "nCounter", "nCounter"),
  spearman = c(
    cor(df$Microarray, df$qPCR, method = "spearman", use = "p"),
    cor(df$Microarray, df$nCounter, method = "spearman", use = "p"),
    cor(df$qPCR, df$nCounter, method = "spearman", use = "p")
  ),
  p.value = c(
    cor.test(
      df$Microarray, df$qPCR, method = "spearman", use = "p", exact = TRUE, 
      continuity = TRUE
    )$p.value,
    cor.test(
      df$Microarray, df$nCounter, method = "spearman", use = "p", exact = TRUE,
      continuity = TRUE
    )$p.value,
    cor.test(
      df$qPCR, df$nCounter, method = "spearman", use = "p", exact = TRUE, 
      continuity = TRUE
    )$p.value
  )
)
cors$p.value <- ifelse(cors$p.value == 0, "<10e-16", cors$p.value)
writexl::write_xlsx(
  cors,
  file.path("Results", "Correlations.xlsx")
)
```


# Plot the data
Microarray versus qPCR
```{r message=FALSE, warning=FALSE, fig.width=4.5, fig.height=6.5}
plt <- ggplot(
  df,
  aes(Microarray, qPCR, colour = Label)
)+
  geom_point()+
  geom_smooth(method = "lm", se = FALSE, colour = "gray")+
  scale_y_continuous(
    expand = expand_scale(
      mult = c(0,0.3),
      add = c(0,0)
    ),
    limits = c(0,NA),
    breaks = seq(0,1,0.25)
  )+
  scale_x_continuous(
    expand = expand_scale(
      mult = c(0,0.3),
      add = c(0,0)
    ),
    limits = c(0,NA),
    breaks = seq(0,1,0.25)
  )+
  facet_wrap(~Gene, ncol = 2)+
  coord_equal(xlim = c(0,1.1), ylim = c(0,1.2))+
  xlab("Relative Expression by Microarray")+
  ylab("Relative Expression by qPCR")+
  panel_border(colour = "black", size = 1.2)+
  scale_fill_manual(values = c("#ff4d4d", "#0099ff"))+
  scale_colour_manual(values = c("#ff4d4d", "#0099ff"))+
  theme(
    strip.background = element_blank(),
    panel.spacing = unit(0.7, "lines"),
    legend.title = element_blank(),
    legend.position = c(0.62,0.16),
    axis.text = element_text(size = 10),
    axis.title = element_text(size = 12),
    strip.text = element_text(size = 12, face = "italic")
  )+
  stat_cor(
    aes(group = "AllData"),
    method = "spearman",
    label.x = 0.05, label.y = 1.1,
    show.legend = FALSE, size = 3
  )
  
cowplot::save_plot(
  file.path("Results","Correlation_Microarray_qPCR.tiff"),
  plt,
  base_width = 4.5, base_height = 6.5
)

plt
```


Microarray versus nCounter
```{r message=FALSE, warning=FALSE, fig.width=4.5, fig.height=6.5}
plt <- ggplot(
  df,
  aes(Microarray, nCounter, colour = Label)
)+
  geom_point()+
  geom_smooth(method = "lm", se = FALSE, colour = "gray")+
  scale_y_continuous(
    expand = expand_scale(
      mult = c(0,0.3),
      add = c(0,0)
    ),
    limits = c(0,NA),
    breaks = seq(0,1,0.25)
  )+
  scale_x_continuous(
    expand = expand_scale(
      mult = c(0,0.3),
      add = c(0,0)
    ),
    limits = c(0,NA),
    breaks = seq(0,1,0.25)
  )+
  facet_wrap(~Gene, ncol = 2)+
  coord_equal(xlim = c(0,1.1), ylim = c(0,1.2))+
  xlab("Relative Expression by Microarray")+
  ylab("Relative Expression by nCounter")+
  panel_border(colour = "black", size = 1.2)+
  scale_fill_manual(values = c("#ff4d4d", "#0099ff"))+
  scale_colour_manual(values = c("#ff4d4d", "#0099ff"))+
  theme(
    strip.background = element_blank(),
    panel.spacing = unit(0.7, "lines"),
    legend.title = element_blank(),
    legend.position = c(0.62,0.16),
    axis.text = element_text(size = 10),
    axis.title = element_text(size = 12),
    strip.text = element_text(size = 12, face = "italic")
  )+
  stat_cor(
    aes(group = "AllData"),
    method = "spearman",
    label.x = 0.05, label.y = 1.1,
    show.legend = FALSE, size = 3
  )
  
cowplot::save_plot(
  file.path("Results","Correlation_Microarray_nCounter.tiff"),
  plt,
  base_width = 4.5, base_height = 6.5
)

plt
```


qPCR versus nCounter
```{r message=FALSE, warning=FALSE, fig.width=4.5, fig.height=6.5}
plt <- ggplot(
  df,
  aes(qPCR, nCounter, colour = Label)
)+
  geom_point()+
  geom_smooth(method = "lm", se = FALSE, colour = "gray")+
  scale_y_continuous(
    expand = expand_scale(
      mult = c(0,0.3),
      add = c(0,0)
    ),
    limits = c(0,NA),
    breaks = seq(0,1,0.25)
  )+
  scale_x_continuous(
    expand = expand_scale(
      mult = c(0,0.3),
      add = c(0,0)
    ),
    limits = c(0,NA),
    breaks = seq(0,1,0.25)
  )+
  facet_wrap(~Gene, ncol = 2)+
  coord_equal(xlim = c(0,1.1), ylim = c(0,1.2))+
  xlab("Relative Expression by qPCR")+
  ylab("Relative Expression by nCounter")+
  panel_border(colour = "black", size = 1.2)+
  scale_fill_manual(values = c("#ff4d4d", "#0099ff"))+
  scale_colour_manual(values = c("#ff4d4d", "#0099ff"))+
  theme(
    strip.background = element_blank(),
    panel.spacing = unit(0.7, "lines"),
    legend.title = element_blank(),
    legend.position = c(0.62,0.16),
    axis.text = element_text(size = 10),
    axis.title = element_text(size = 12),
    strip.text = element_text(size = 12, face = "italic")
  )+
  stat_cor(
    aes(group = "AllData"),
    method = "spearman",
    label.x = 0.05, label.y = 1.1,
    show.legend = FALSE, size = 3
  )+
  panel_border(colour = "black", size = 1.2)+
  scale_fill_manual(values = c("#ff4d4d", "#0099ff"))+
  scale_colour_manual(values = c("#ff4d4d", "#0099ff"))+
  theme(
    strip.background = element_blank(),
    panel.spacing = unit(0.7, "lines"),
    legend.title = element_blank(),
    legend.position = c(0.62,0.16),
    axis.text = element_text(size = 10),
    axis.title = element_text(size = 12),
    strip.text = element_text(size = 12, face = "italic")
  )+
  stat_cor(
    aes(group = "AllData"),
    method = "spearman",
    label.x = 0.05, label.y = 1.1,
    show.legend = FALSE, size = 3
  )
  
cowplot::save_plot(
  file.path("Results","Correlation_qPCR_nCounter.tiff"),
  plt,
  base_width = 4.5, base_height = 6.5
)

plt
```


End of analysis
