---
title: "Platform Comparisons"
always_allow_html: yes
output:
  html_document:
    code_folding: hide
    number_sections: yes
    toc: yes
    toc_depth: 5
    theme: united
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Overview
This script merges ROC curves generated by other analyses into a single plot.


# Prepare the environment
```{r message=FALSE, warning=FALSE}
# Load packages.
library(magrittr) # Pipe operator.
library(ggplot2) # Plotting
library(cowplot) # Plotting.
theme_set(theme_cowplot())

# Create the Results folder.
if(dir.exists("Results")){
  unlink("Results", recursive = TRUE, force = TRUE)
}
dir.create("Results")
```


# Prepare the data
```{r message=FALSE, warning=FALSE}
nCounter_internal_threshold <- readxl::read_excel(
  file.path("Data", "nCounter_Internal_Threshold.xlsx")
)

microarray_internal_threshold <- readxl::read_excel(
  file.path("Data", "Microarray_Internal_Threshold.xlsx")
)

microarray_external_threshold <- readxl::read_excel(
  file.path("Data", "Microarray_External_Threshold.xlsx")
)

nCounter_internal_data <- readxl::read_excel(
  file.path("Data", "nCounter_Internal_Samples.xlsx")
) %>%
  dplyr::mutate(Platform = "nCounter")

microarray_data <- readxl::read_excel(
  file.path("Data", "Microarray_Samples.xlsx")
) %>%
  dplyr::mutate(Platform = "Microarray")

all_data <- dplyr::bind_rows(
  nCounter_internal_data,
  microarray_data
) %>%
  dplyr::select(Group, Probability, Dataset, Platform) %>%
  dplyr::mutate(
    Group = factor(Group, levels = c("AIUP", "ECT")),
    Dataset = factor(Dataset, levels = c("Internal", "External")),
    Platform = factor(Platform, levels = c("Microarray", "nCounter")),
    Label = factor(
      paste(as.character(Dataset), as.character(Platform)),
      levels = c(
        "Internal Microarray", "External Microarray", "Internal nCounter"
      )
    )
  )


imd <- dplyr::filter(
  all_data,
  Label == "Internal Microarray"
)

emd <- dplyr::filter(
  all_data,
  Label == "External Microarray"
)

ind <- dplyr::filter(
  all_data,
  Label == "Internal nCounter"
)
```


# Plot ROC curves


```{r}
# Plot multiple ROC curves in one figure.
plot_multiple_roc <- function(data_list, show_threshold = TRUE){
  # Initialize the plot.
  plt <- ggplot()+
    coord_equal(xlim = c(0,1), ylim = c(0,1))+
    panel_border(colour = "black", size = 1.2)+
    geom_segment(
      aes(
        x = 0, y = 0,
        xend = 1, yend = 1
      ),
      colour = "black", linetype = "dashed", size = 0.5, alpha = 0.4
    )+
    xlab("1 - Specificity")+ylab("Sensitivity")
  
  # Add elements for each ROC curve.
  threshold_tbl <- tibble::tibble()
  threshold_points_tbl <- tibble::tibble()
  for(group in names(data_list)){
    roc_obj <- pROC::roc(
      response = as.numeric(data_list[[group]]$df$Group) - 1,
      predictor = data_list[[group]]$df$Probability
    )
    roc_df <- tibble::tibble(
      sensitivity = roc_obj$sensitivities,
      `1-specificity` = 1-roc_obj$specificities
    )
    threshold_indices <- c(
      tail(which(roc_obj$thresholds <= 
                   data_list[[group]]$rocr_threshold$Threshold), 1),
      head(which(roc_obj$thresholds >= 
                   data_list[[group]]$rocr_threshold$Threshold), 1)
    ) %>% sort()
    plt <- plt+
      geom_path(
        data = roc_df,
        mapping = aes(`1-specificity`, sensitivity),
        colour = data_list[[group]]$colour,
        size = 1.2
      )
    if(show_threshold){
      if(length(threshold_indices) == 1){
        threshold_points_tbl <- dplyr::bind_rows(
          threshold_points_tbl,
          tibble::tibble(
            x = (1-roc_obj$specificities)[threshold_indices][1],
            y = roc_obj$sensitivities[threshold_indices][1]
          )
        )
      }
      if(length(threshold_indices) == 2){
        seg_ends <- tibble::tibble(
          sensitivity = roc_obj$sensitivities[threshold_indices],
          `1-specificity` = (1-roc_obj$specificities)[threshold_indices]
        )
        threshold_tbl <- dplyr::bind_rows(
          threshold_tbl,
          tibble::tibble(
            x = seg_ends$`1-specificity`[1],
            y = seg_ends$sensitivity[1],
            xend = seg_ends$`1-specificity`[2],
            yend = seg_ends$sensitivity[2]
          )
        )
      }
    }
  }
  if(show_threshold){
    if(nrow(threshold_tbl) > 0){
      plt <- plt+
        geom_segment(
          data = threshold_tbl,
          mapping = aes(x = x, y = y, xend = xend, yend = yend),
          colour = "black", size = 1.5
        )
    }
    if(nrow(threshold_points_tbl) > 0){
      plt <- plt+
        geom_point(
          data = threshold_points_tbl,
          mapping = aes(x, y),
          colour = "black", size = 1.5
        )
    }
  }
  colour_values <- sapply(data_list, function(x){x[["colour"]]})
  plt+
    geom_line(
      data = tibble::tibble(
        group = factor(rep(names(data_list),2), levels = names(data_list)),
        x = rep(c(-1,-2), each = length(data_list)),
        y = rep(c(-1,-2), each = length(data_list))
      ),
      mapping = aes(x, y, colour = group),
      show.legend = TRUE,
      size = 1.2
    )+
    scale_colour_manual(
      name = "Legend",
      values = colour_values
    )+
    theme(
      legend.position = c(0.4,0.6),
      legend.title = element_blank()
    )
}
plt <- plot_multiple_roc(
  list(
    "Internal Microarray" = list("df" = imd, 
                      "rocr_threshold" = nCounter_internal_threshold,
                      "colour" = "#ff4d4d"),
    "External Microarray" = list("df" = emd, 
                      "rocr_threshold" = microarray_internal_threshold,
                      "colour" = "#0099ff"),
    "Internal nCounter" = list("df" = ind, 
                      "rocr_threshold" = microarray_external_threshold,
                      "colour" = "#009933")
  ),
  show_threshold = FALSE
)
cowplot::save_plot(
  file.path("Results", "Merged_ROC.tiff"),
  plt,
  base_width = 5.5, base_height = 4
)
```


End of analysis
